baseURL = 'https://dccxxv.dev/'
languageCode = 'en-US'
title = 'DCCXXV.DEV'
theme = 'haiku'

[menus]
[[menu.main]]
identifier = "about"
name = "About"
pageRef = "/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "Projects"
title = "Projects"
pageRef = "/projects/"
weight = 2

[[menu.main]]
identifier = "github"
name = "Github"
title = "GitHub"
url = "https://github.com/DCCXXV"
weight = 3
