name = "slate"
license = "MIT"
licenselink = "https://github.com/dccxxv/slate/LICENSE"
description = "A minimal and customizable theme for hugo."
homepage = "https://github.com/dccxxv/slate"
tags = ["portfolio", "minimal", "personal"]
min_version = "0.41"

[author]
name = "DCCXXV"
homepage = "https://dccxxv.dev"
