baseURL = 'https://dccxxv.dev/'
languageCode = 'es-es'
title = 'Blog de DCCXXV'
theme = 'not-much'
showThemeNotice = true

[params]
theme = "dark"
palette = "catpuccin"

[[menu.main]]
  identifier = "inicio"
  name = "inicio"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "sobre mí"
  title = "Sobre mí"
  url = "/about"
  weight = 2

[[menu.main]]
  identifier = "posts"
  name = "publicaciones"
  title = "Publicaciones"
  url = "/posts"
  weight = 3

[[menu.main]]
  identifier = "github"
  name = "github"
  title = "GitHub"
  url = "https://github.com/DCCXXV"
  weight = 4
